# Generated by Django 3.1.7 on 2021-04-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.boss')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('player_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.playerclass')),
            ],
        ),
        migrations.CreateModel(
            name='LootList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.player')),
            ],
        ),
        migrations.AddField(
            model_name='boss',
            name='dungeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dungeon'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_uptime', models.IntegerField()),
                ('raid_parse_average', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.player')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.raid')),
            ],
        ),
    ]
